# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_DownloaderMain.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DownloaderMain(object):
    def setupUi(self, DownloaderMain):
        DownloaderMain.setObjectName("DownloaderMain")
        DownloaderMain.resize(901, 711)
        self.centralwidget = QtWidgets.QWidget(DownloaderMain)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.URLSettingBtn = QtWidgets.QPushButton(self.centralwidget)
        self.URLSettingBtn.setObjectName("URLSettingBtn")
        self.horizontalLayout_2.addWidget(self.URLSettingBtn)
        self.DownloadResultBtn = QtWidgets.QPushButton(self.centralwidget)
        self.DownloadResultBtn.setObjectName("DownloadResultBtn")
        self.horizontalLayout_2.addWidget(self.DownloadResultBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.StartDownloadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.StartDownloadBtn.setObjectName("StartDownloadBtn")
        self.horizontalLayout_3.addWidget(self.StartDownloadBtn)
        self.PauseDownloadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.PauseDownloadBtn.setObjectName("PauseDownloadBtn")
        self.horizontalLayout_3.addWidget(self.PauseDownloadBtn)
        self.StopDownloadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.StopDownloadBtn.setObjectName("StopDownloadBtn")
        self.horizontalLayout_3.addWidget(self.StopDownloadBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        DownloaderMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DownloaderMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 901, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        DownloaderMain.setMenuBar(self.menubar)
        self.actionQuit = QtWidgets.QAction(DownloaderMain)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(DownloaderMain)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSystem_Config = QtWidgets.QAction(DownloaderMain)
        self.actionSystem_Config.setObjectName("actionSystem_Config")
        self.actionURL = QtWidgets.QAction(DownloaderMain)
        self.actionURL.setObjectName("actionURL")
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionURL)
        self.menuSetting.addAction(self.actionSystem_Config)
        self.menuSetting.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(DownloaderMain)
        QtCore.QMetaObject.connectSlotsByName(DownloaderMain)

    def retranslateUi(self, DownloaderMain):
        _translate = QtCore.QCoreApplication.translate
        DownloaderMain.setWindowTitle(_translate("DownloaderMain", "Downloader"))
        self.URLSettingBtn.setText(_translate("DownloaderMain", "URL"))
        self.DownloadResultBtn.setText(_translate("DownloaderMain", "下载结果"))
        self.StartDownloadBtn.setText(_translate("DownloaderMain", "开始"))
        self.PauseDownloadBtn.setText(_translate("DownloaderMain", "暂停"))
        self.StopDownloadBtn.setText(_translate("DownloaderMain", "停止"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DownloaderMain", "主播"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DownloaderMain", "标题"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DownloaderMain", "大小"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DownloaderMain", "状态"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("DownloaderMain", "进度"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("DownloaderMain", "下载时间"))
        self.menuFile.setTitle(_translate("DownloaderMain", "File"))
        self.menuEdit.setTitle(_translate("DownloaderMain", "Edit"))
        self.menuSetting.setTitle(_translate("DownloaderMain", "Setting"))
        self.menuHelp.setTitle(_translate("DownloaderMain", "Help"))
        self.actionQuit.setText(_translate("DownloaderMain", "Quit"))
        self.actionAbout.setText(_translate("DownloaderMain", "About"))
        self.actionSystem_Config.setText(_translate("DownloaderMain", "System Config"))
        self.actionURL.setText(_translate("DownloaderMain", "URL"))
