# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_DownloaderMain.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConverterMain(object):
    def setupUi(self, ConverterMain):
        ConverterMain.setObjectName("ConverterMain")
        ConverterMain.resize(901, 711)
        self.centralwidget = QtWidgets.QWidget(ConverterMain)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.URLSettingBtn = QtWidgets.QPushButton(self.centralwidget)
        self.URLSettingBtn.setObjectName("URLSettingBtn")
        self.horizontalLayout_2.addWidget(self.URLSettingBtn)
        self.DownloadResultBtn = QtWidgets.QPushButton(self.centralwidget)
        self.DownloadResultBtn.setObjectName("DownloadResultBtn")
        self.horizontalLayout_2.addWidget(self.DownloadResultBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.StartDownloadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.StartDownloadBtn.setObjectName("StartDownloadBtn")
        self.horizontalLayout_3.addWidget(self.StartDownloadBtn)
        self.PauseDownloadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.PauseDownloadBtn.setObjectName("PauseDownloadBtn")
        self.horizontalLayout_3.addWidget(self.PauseDownloadBtn)
        self.StopDownloadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.StopDownloadBtn.setObjectName("StopDownloadBtn")
        self.horizontalLayout_3.addWidget(self.StopDownloadBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.download_info_table_show = QtWidgets.QTableWidget(self.centralwidget)
        self.download_info_table_show.setObjectName("download_info_table_show")
        self.download_info_table_show.setColumnCount(7)
        self.download_info_table_show.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.download_info_table_show.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.download_info_table_show.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.download_info_table_show.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.download_info_table_show.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.download_info_table_show.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.download_info_table_show.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.download_info_table_show.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.download_info_table_show)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        ConverterMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ConverterMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 901, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        ConverterMain.setMenuBar(self.menubar)
        self.actionQuit = QtWidgets.QAction(ConverterMain)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(ConverterMain)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSystem_Config = QtWidgets.QAction(ConverterMain)
        self.actionSystem_Config.setObjectName("actionSystem_Config")
        self.actionURL = QtWidgets.QAction(ConverterMain)
        self.actionURL.setObjectName("actionURL")
        self.actionUser_Config = QtWidgets.QAction(ConverterMain)
        self.actionUser_Config.setObjectName("actionUser_Config")
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionURL)
        self.menuSetting.addAction(self.actionUser_Config)
        self.menuSetting.addAction(self.actionSystem_Config)
        self.menuSetting.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(ConverterMain)
        QtCore.QMetaObject.connectSlotsByName(ConverterMain)

    def retranslateUi(self, ConverterMain):
        _translate = QtCore.QCoreApplication.translate
        ConverterMain.setWindowTitle(_translate("ConverterMain", "Converter"))
        self.URLSettingBtn.setText(_translate("ConverterMain", "URL"))
        self.DownloadResultBtn.setText(_translate("ConverterMain", "下载结果"))
        self.StartDownloadBtn.setText(_translate("ConverterMain", "开始"))
        self.PauseDownloadBtn.setText(_translate("ConverterMain", "暂停"))
        self.StopDownloadBtn.setText(_translate("ConverterMain", "停止"))
        item = self.download_info_table_show.horizontalHeaderItem(0)
        item.setText(_translate("ConverterMain", "序号"))
        item = self.download_info_table_show.horizontalHeaderItem(1)
        item.setText(_translate("ConverterMain", "主播ID"))
        item = self.download_info_table_show.horizontalHeaderItem(2)
        item.setText(_translate("ConverterMain", "标题"))
        item = self.download_info_table_show.horizontalHeaderItem(3)
        item.setText(_translate("ConverterMain", "状态"))
        item = self.download_info_table_show.horizontalHeaderItem(4)
        item.setText(_translate("ConverterMain", "类型"))
        item = self.download_info_table_show.horizontalHeaderItem(5)
        item.setText(_translate("ConverterMain", "下载时间"))
        item = self.download_info_table_show.horizontalHeaderItem(6)
        item.setText(_translate("ConverterMain", "大小"))
        self.menuFile.setTitle(_translate("ConverterMain", "File"))
        self.menuEdit.setTitle(_translate("ConverterMain", "Edit"))
        self.menuSetting.setTitle(_translate("ConverterMain", "Setting"))
        self.menuHelp.setTitle(_translate("ConverterMain", "Help"))
        self.actionQuit.setText(_translate("ConverterMain", "Quit"))
        self.actionAbout.setText(_translate("ConverterMain", "About"))
        self.actionSystem_Config.setText(_translate("ConverterMain", "System Config"))
        self.actionURL.setText(_translate("ConverterMain", "URL"))
        self.actionUser_Config.setText(_translate("ConverterMain", "User Config"))


